Require qbs 1.9.0
With 644b224 we introduced changes that for some reason are incompatible
with qbs < 1.9.0, it fails with:

ERROR: /opt/qtcreator-4.3.0/share/qtcreator/qbs/share/qbs/imports/qbs/base/Library.qbs:43:15 The 'profiles' property cannot be an empty list.